# Compiler Construction 2014
# Computer Laboratory 
# University of Cambridge 
# Timothy G. Griffin (tgg22@cam.ac.uk) 

# makefile for vsm.2 

# assumes gcc is installed! 
FLAGS = -pedantic -Wall -ansi
CC = gcc

all:
	$(CC) $(FLAGS) vsm.c main.c -o vsm2

clean:
	rm -f vsm2